### ISSUE TITLE
Missing Images for ServerViewer

### ISSUE THREAD

**Issue by TimmKroe** [theomessin/ts-framework#1]
There are a lot of missing Images for the Server Viewer:

![image](https://user-images.githubusercontent.com/27803956/41119676-acfee20c-6a93-11e8-9888-f5e36e30ac55.png)

I could add them if you want me to do so.

**Comment by theomessin** [comment]
Hiya, I really don't use Teamspeak anymore so this package is no longer supported. :disappointed:
